## Quiz #0101

#### Provide the answers in Python code:

1).  In the class A, students' heights are:

161.5 <br>
165.9 <br>
168.7 <br>
163.1 <br>
170.8 <br>
167.2 <br>

Calculate the mean height by using Python 'list' and 'for' loop:

In [ ]:
class_a=(161.5,165.9,168.7,163.1,170.8,167.2)
class_a=list(class_a)
print(class_a)
mean_height=0
for height in class_a:
  mean_height += height/len(class_a)
print(f'mean heat is {mean_height}')

[161.5, 165.9, 168.7, 163.1, 170.8, 167.2]
mean heat is 166.20000000000002


2).  In the class B, students' heights are:

172.5 <br>
162.9 <br>
161.7 <br>
160.1 <br>
161.8 <br>
169.2 <br>

Calculate the mean height by using Python 'list' and 'for' loop:

In [ ]:
class_b=(172.5,162.9,161.7,160.1,161.8,169.2)
class_a=list(class_b)
print(class_b)
mean_height=0
for height in class_b:
  mean_height += height/len(class_b)
print(f'mean heat is {mean_height}')

(172.5, 162.9, 161.7, 160.1, 161.8, 169.2)
mean heat is 164.7


3). The class A and the class B are joined together to form the class AB. Calculate the mean height by using Python 'list' and 'for' loop:

In [ ]:
class_a =(161.5,165.9,168.7,163.1,170.8,167.2)
class_b = (172.5,162.9,161.7,160.1,161.8,169.2)
class_ab = map(lambda x, y: (x + y)/2, class_a, class_b)
print(list(class_ab))



[167.0, 164.4, 165.2, 161.6, 166.3, 168.2]


4). Sort the heights of the class AB.

In [ ]:
class_ab=[167.0, 164.4, 165.2, 161.6, 166.3, 168.2]
x=class_ab.sort()

None


5). The class C is formed with students with the height less than 165. Make a list 'C' containing the heights of the class C.

In [ ]:
class_ab=[167.0, 164.4, 165.2, 161.6, 166.3, 168.2]
c=[]
for i in class_ab:
  if(i < 165):
    c.append(i)
print(c)


[164.4, 161.6]


6). The class D is formed with students with the height larger than 160 and less than 170. Make a list containing the heights of the class D.

In [ ]:
class_ab=[167.0, 164.4, 165.2, 161.6, 166.3, 168.2]
c=[]
for i in class_ab:
  if(i >160 and i< 170):
    c.append(i)
print(c)

[167.0, 164.4, 165.2, 161.6, 166.3, 168.2]
